biocypher:
  debug: true
  head_ontology:
    root_node: entity
    url: https://github.com/biolink/biolink-model/raw/v3.2.1/biolink-model.owl.ttl
  offline: true
  schema_config_path: schema_config_1.yaml
neo4j:
  array_delimiter: '|'
  database_name: test
  delimiter: ;
  import_call_bin_prefix: ''
  multi_db: false
  skip_bad_relationships: true
  skip_duplicate_nodes: true
  wipe: true
